#!/usr/bin/env python

import sys
import os.path
import logging
import geojson

import mapzen.whosonfirst.search
import mapzen.whosonfirst.utils

if __name__ == '__main__':

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
    options, args = opt_parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.WARNING)

    idx = mapzen.whosonfirst.search.index()

    for path in args:
        path = os.path.abspath(path)
        idx.index_file(path)

    sys.exit()

