#!/usr/bin/env python

import sys
import os.path
import logging
import geojson

import mapzen.whosonfirst.utils

# See this - it is poorly namespaced. It needs to be improved but this involves
# becoming angry because that is what namespaces in Python do. So I am not doing
# it today... (20150730/thisisaaronland)

import whosonfirst

if __name__ == '__main__':

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-s', '--source', dest='source', action='store', default=None, help='Where to read files from')
    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
    options, args = opt_parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    # See above inre namespaces
    idx = whosonfirst.search()

    source = os.path.abspath(options.source)
    crawl = mapzen.whosonfirst.utils.crawl(source)

    rsp = idx.index_files(crawl)
    print rsp

